#!/bin/sh

# (c) 2008 Jasper Spaans <j@jasper.es>

worst=0

msg=""

for dev in /dev/md?* ; do \

  mdadm --misc -t $dev

  status=$?

  if [ $status == 0 ]; then

    msg="${msg} ${dev}: ok"

  elif [ $status == 1 ] ; then

    if [ worst != 2 ] ; then

      worst=1

    fi

    msg="${msg} ${dev}: degraded"

  elif [ $status == 2 ] ; then

    worst=2

    msg="${msg} ${dev}: unusable"

  fi

done



echo $msg

exit $worst
