#!/usr/bin/perl -w
#
# Copyright (C) 2008 Rodolphe Quiedeville <rodolphe@quiedeville.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# Plugin to monitor number of sip objects
#
# Works with Asterisk 1.4.21
#
#%# family=asterisk

use strict;

if ($ARGV[0] and $ARGV[0] eq "config")
{
    print "graph_title Asterisk sip objects\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_vlabel peers\n";
    print "graph_category asterisk\n";
    print "static.draw AREA\n";
    print "static.label static\n";
    print "realtime.draw STACK\n";
    print "realtime realtime\n";
    print "autocreate.draw STACK\n";
    print "autocreate.label autocreate\n";
    exit 0;
}

open(LINE, 'asterisk -rx "sip show objects"|');

my ($static, $realtime, $auto)=(0,0,0);

while (<LINE>)
{
    if ($_ =~ /^-= Peer objects: (\d+) static, (\d+) realtime, (\d+) autocreate/) 
    {
	$static = $1;
	$realtime = $2;
	$auto = $3;
    }
}

close(LINE);

# print results on STDOUT
printf "static.value %d\n", $static;
printf "realtime.value %d\n", $realtime;
printf "autocreate.value %d\n", $auto;
