#!/usr/bin/perl -w
#
# Copyright (C) 2005-2008 Rodolphe Quiedeville <rodolphe@quiedeville.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# If you improve this script please send your version to my email address
# with the copyright notice upgrade with your name.
#
# Plugin to monitor number of messages in all voicemails
#
#%# family=asterisk

use strict;

if ($ARGV[0] and $ARGV[0] eq "config")
{
    my %contexts;
    print "graph_title Asterisk Voicemail messages\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_vlabel messages\n";
    print "graph_category asterisk\n";

    open(LINE, 'asterisk -rx "voicemail show users"|');

    while (<LINE>)
    {
	if ($_ =~ /^(\w+)\s+(.*)\s+(\d+)$/)
	{
	    $contexts{$1} = $1;
	}
    }
    
    close(LINE);
    my $i = 0;
    foreach my $context (keys %contexts)
    {
	my $type = $i ? "STACK" : "AREA";
	printf "%s.draw %s\n%s.label %s\n", $context, $type, $context, $context;
	$i++;
    }


    exit 0;
}

open(LINE, 'asterisk -rx "voicemail show users"|');

my %results;

while (<LINE>)
{
    $results{$1} += $3 if ($_ =~ /^(\w+)\s+(.*)\s+(\d+)$/);
}

close(LINE);

foreach my $key (keys %results)
{
    printf "%s.value %s\n", $key, $results{$key};
}
