#!/usr/bin/perl -w
#
# Copyright (C) 2008 Rodolphe Quiedeville <rodolphe@quiedeville.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# Plugin to monitor lag on IAX active channels
#
# Add the following lines to MUNINDIR/plugin-conf.d/munin-node
# [asterisk_*]
# user root
#
#%# family=asterisk

use strict;

if ($ARGV[0] and $ARGV[0] eq "config")
{
    print "graph_title Asterisk iax lag\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_vlabel ms\n";
    print "graph_category asterisk\n";
    print "lag.label lag (ms)\n";
    print "lag.draw LINE1\n";
    exit 0;
}

open(LINE, 'asterisk -rx "iax2 show channels"|');

my ($lag, $i)=(0,0);

while (<LINE>)
{
    if ($_ =~ /-?(\d+)ms\s+-?\d+ms\s+-?\d+ms\s+(\w+)/) 
    {
	$lag += $1;
	$i++;
    }
}

close(LINE);

printf "lag.value %.2f\n", ($lag/$i);
