#!/usr/bin/perl -w
#
# Copyright (C) 2005-2008 Rodolphe Quiedeville <rodolphe@quiedeville.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# Plugin to monitor number of IAX active channels by codec used
#
# Add the following lines to MUNINDIR/plugin-conf.d/munin-node
# [asterisk_*]
# user root
#
# Optional parameters:
#       codecs
#
#%# family=asterisk

use strict;

# if you want to graph all available codecs
#my @CODECS = qw(g723 gsm ulaw alaw g726 adpcm slin lpc10 g729 speex ilbc);

my @CODECS = exists $ENV{'codecs'} ? split ' ',$ENV{'codecs'} : qw(alaw gsm ulaw g729);

if ($ARGV[0] and $ARGV[0] eq "config")
{
    print "graph_title Asterisk iax channels/codecs\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_vlabel channels\n";
    print "graph_category asterisk\n";
    foreach my $codec (@CODECS) {
	if ($codec eq $CODECS[0]) {
	    print "$codec.draw AREA\n";
	}
	else{
	    print "$codec.draw STACK\n";
	}
	print "$codec.label $codec\n";
    }
    exit 0;
}


my %results;
# we initialize the results
$results{$_} = 0 foreach (@CODECS);

open(LINE, 'asterisk -rx "iax2 show channels"|');

while (<LINE>)
{
    $results{$1}++ if ($_ =~ /-?\d+ms\s+-?\d+ms\s+-?\d+ms\s+(\w+)/);
}

close(LINE);

# print results on STDOUT
foreach my $codec (@CODECS) {
    printf "%s.value %d\n", $codec, $results{$codec};
}

