#!/usr/bin/perl -w
#
# Copyright (C) 2005-2008 Rodolphe Quiedeville <rodolphe@quiedeville.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Plugin to monitor number of active channels by type
#
# Add the following lines to MUNINDIR/plugin-conf.d/munin-node
# [asterisk_*]
# user root
#
#
#%# family=asterisk

use strict;

my @CHANNELS = exists $ENV{'channels'} ? split ' ',$ENV{'channels'} : qw(Zap IAX2 SIP);

if ($ARGV[0] and $ARGV[0] eq "config")
{
    print "graph_title Asterisk channels\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_vlabel channels\n";
    print "graph_category asterisk\n";
    foreach my $channel (@CHANNELS) {
	if ($channel eq $CHANNELS[0]) {
	    print "$channel.draw AREA\n";
	}
	else{
	    print "$channel.draw STACK\n";
	}
	print "$channel.label $channel\n";
    }
    exit 0;
}

my %results;
foreach my $channel (@CHANNELS) {
    $results{$channel} = 0;
}

open(LINE, 'asterisk -rx "show channels"|');

my ($chans, $calls, $line)=(0,0,undef);

while ($line = <LINE>)
{
    $results{$1}++ if ($line =~ /^(\w+)\//);
}

close(LINE);

foreach my $channel (@CHANNELS) {
    printf "%s.value %d\n", $channel, $results{$channel};
}
