#!/usr/bin/perl -w
#
# Copyright (C) 2006-2007 Rodolphe Quiedeville <rodolphe@quiedeville.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# If you improve this script please send your version to my email address
# with the copyright notice upgrade with your name.
#
# Plugin to monitor number of active user un a special room
#
# $Log$
# Revision 1.1  2007/01/17 10:46:01  rodo
# Change incorrect family
#
# Revision 1.0  2006/02/26 21:04:01  rodo
# Created by Rodolphe Quiedeville
#
# Parameters mandatory:
#
# 	username
# 	secret
#
#%# family=manual
#%# capabilities=autoconf

use strict;

my $ret = undef;
if (! eval "require Net::Telnet;")
{
    $ret = "Net::Telnet not found";
}

$0 =~ /asterisk_meetme_(.+)*$/;
my $confnum = $1;
exit 2 unless defined $confnum;

if ($ARGV[0] and $ARGV[0] eq "config")
{
    print "graph_title Asterisk actives users in room $confnum\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_vlabel users\n";
    print "graph_category asterisk\n";
    print "users.draw AREA\n";
    print "users.label users\n";
    exit 0;
}

my $host = exists $ENV{'host'} ? $ENV{'host'} : "127.0.0.1";
my $port = exists $ENV{'port'} ? $ENV{'port'} : "5038";

my $username = $ENV{'username'};
my $secret   = $ENV{'secret'};

my $pop = new Net::Telnet (Telnetmode => 0);
$pop->open(Host => $host,
	   Port => $port);

## Read connection message.
my $line = $pop->getline;
die $line unless $line =~ /^Asterisk/;

## Send user name.
$pop->print("Action: login");
$pop->print("Username: $username");
$pop->print("Secret: $secret");
$pop->print("Events: off");
$pop->print("");

## Request status of messages.
$pop->print("Action: command");
$pop->print("Command: meetme");
$pop->print("");

#Response: Follows
#Conf Num       Parties        Marked     Activity  Creation
#5500           0001           N/A        00:00:03  Static
#* Total number of MeetMe users: 1
#--END COMMAND--

my ($users, $start)=(0,0);

while (($line = $pop->getline) and ($line !~ /Total number|No active MeetMe/o))
{
    if ($start) {
	my @datas = split ' ', $line;
	$users = $datas[1] if ($datas[0] = $confnum);
    }

    $start = 1 if ($line =~ /Conf\sNum\s*Parties/o);
}

$pop->print("Action: logoff");
$pop->print("");

print "users.value $users\n";

# vim:syntax=perl
