#!/bin/sh
#
# Script to monitor amount of memory which has not yet been been allocated to a
# Xen domain.
#
# Parameters understood:
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#
# Magic markers (optional - used by munin-config and installation
# scripts):
#
#%# family=manual
#%# capabilities=autoconf

MAXLABEL=20
MAXNAME=15

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Unallocated memory'
	echo 'graph_args --base 1024 --lower-limit 0'
	echo 'graph_vlabel bytes'
	echo 'graph_category Xen'
	echo 'graph_total Total'
	echo "free_memory.label free memory"
	echo "free_memory.cdef free_memory,1024,*,1024,*"
	exit 0
fi

xm info | grep ^free_memory | while read label separator value; do
	echo "free_memory.value $value"
done
