#!/usr/bin/python

from sys import argv
import httplib, re

url = "/cache_status"

matches = re.search('_([0-9]+)$', argv[0])
if matches and len(matches.groups()) > 0:
	port = matches.groups()[0]
else:
	port = 8080

connection = httplib.HTTPConnection("localhost", port)

if len(argv) > 1 and argv[1] == 'config':
	print """\
graph_title Zope database cache
graph_category Zope
graph_vlabel objects
graph_info Cache utilization of the ZODB. """

	print """\
objects_total.label total
objects_total.info Total number of objects in the database
objects_cached.label in memory
objects_cached.info Total number of objects in memory from all caches
objects_target.label target
objects_target.info Target number of objects in memory per cache"""

else:
	connection.request("GET", url)
	result = connection.getresponse()
	data = result.read().strip()
	connection.close()

	(objects_total, objects_cached, objects_target) = data.split()

	print 'objects_total.value', objects_total
	print 'objects_cached.value', objects_cached
	print 'objects_target.value', objects_target
